import type { NextPage } from "next";
import Head from "next/head";
import React from "react";
import { HomeCointainer } from "../styles/components/home";

const Home: NextPage = () => {
  return (
    <HomeCointainer>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex justify-center items-center flex-col">
        <h1 className="text-white font-bold text-2xl">New Project</h1>
        <h2 className="text-white/80 font-medium mt-1">By Jão</h2>
      </main>
    </HomeCointainer>
  );
};

export default Home;
